export const Actions = {
    ADD_TO_CART = "ADD_TO_CART",
    ADD_MULTIPLE_TO_CART = "ADD_MULTIPLE_TO_CART",
    REMOVE_FROM_CART = "REMOVE_FROM_CART",
    CLEAR_CART = "CLEAR_CART",
    UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY",
    TOGGLE_CART = "TOGGLE_CART",
    UPDATE_CATEGORIES = "UPDATE_CATEGORIES",
    UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY",
    UPDATE_PRODUCTS = "UPDATE_PRODUCTS"
};


